### PR TITLE
Converted iOS powershell tasks to typescript

### PR DESCRIPTION
**Pull request by ahoefling**
Updated iOSBumpVersion and iOSBundleIdentifier from powershell to typescript, this PR fixes 1/2 of #4 . This is my first attempt at typescript so stuff isn't perfect but it is good enough to run the builds.

**Build Agent Pre-Req**
This may become a problem, but I was unable to include the node module `tsd`. I added it globally for now until we can figure out a better way to do this. I mentioned this in the issue #4 

**Test Cases**
I published the tasks onto my local mac build agent and was able to run them successfully.

**Publishing**
To properly publish these out to the marketplace run the following commands

1. navigate to `tasks/iOSBumpVersion`
    1. exec `npm install` to download node dependencies
    2. exec `tsc` to build js task
2. navigate to `tasks/iOSBundleIdentifier`
    1. exec `npm install` to download node dependencies
    2. exec `tsc` to build js task
3. exec `tfx extension create --manifest-globs vss-extension.json`
4. publish the `vsix` file to the marketplace

This PR only contains the iOS updates, I ran out of time and I am will be on vacation for the next 2 weeks. I wanted to get something submitted before leaving.

### CODE REVIEW

**Comment by ahoefling** [comment]
@jamesmontemagno do you have a plan for this PR? Are we waiting for powershell core support? Do you want me to add android support?

I was able to publish this code to my personal VSTS marketplace account as a private extension and have it working in my build environment

**Comment by jamesmontemagno** [comment]
I can pull these in. I can try to do Android too today  maybe :)

**Comment by ahoefling** [comment]
If you run into issues I should be able to tackle it sometime next week, just let me know

**Comment by jamesmontemagno** [comment]
@ahoefling is iOSBundleIdentifier  actually done? I only see:

  // requires parameters
        if(!isNullOrUndefined(sourcePath))
        {
            throw new Error("[!] Missing required input: sourcePath");
        }
        
        

        
        console.log('Task done!');

**Comment by ahoefling** [comment]
Looks like I never saved the file - 
image

I'm going to push changes back to this branch

**Comment by jamesmontemagno** [comment]
no worries
i got it :)

**Comment by ahoefling** [comment]
Oops, I'll delete my other PR

**Pull request merged**
